### ISSUE TITLE
can't get the project

### ISSUE THREAD

**Issue by j-khong** [jankapunkt/meteor-autoform-bpmn-example#1]
git clone git@github.com:jankapunkt/meteor-autoform-bpmn-example.git
Cloning into 'meteor-autoform-bpmn-example'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by jankapunkt** [comment]
Hi @j-khong 

Do you have set an ssh key in your github settings?

**Comment by j-khong** [comment]
my bad
